### PR TITLE
Fixed api url and unit test

### PR DESCRIPTION
**Pull request by TurtleBeatboxer**
#11 Unit test was actually impossible to be completed due to google translator translating it other way around.
@goxr3plus

### CODE REVIEW

**Comment by goxr3plus** [comment]
Don't worry about unit tests we yolo ☺

**Comment by goxr3plus** [comment]
Did you tested that it works correctly?

**Comment by TurtleBeatboxer** [comment]
Does it not?

**Comment by TurtleBeatboxer** [comment]
I did unit test that translates Hola . buenos dias and takes response in english. Nothing beside that

**Pull request merged**
